package:
	sam package \
		--template-file template.yml \
		--output-template-file packaged.yml \
		--s3-bucket pypy-examples-us-east-1 \
		--region us-east-1

deploy: package
	aws cloudformation deploy \
		--template-file packaged.yml \
		--stack-name pypy-example-sam \
		--capabilities CAPABILITY_IAM \
		--parameter-overrides PyPyLayerArn=$$PYPY_LAYER_ARN \
		--region us-east-1

local-build:
	$(MAKE) -C ../.. local-build

local-invoke:
	$(MAKE) -C ../.. local-invoke
