AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "PyPy Runtime local SAM example"

Resources:
  PyPyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: local-pypy-runtime
      ContentUri: ../../.local-layer
      CompatibleRuntimes:
        - provided.al2023

  HelloFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: hello/
      Handler: hello.handler
      Runtime: provided.al2023
      Layers:
        - !Ref PyPyLayer
      Timeout: 10
      MemorySize: 256
